/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /user/x0221391/ros_ws/src/catch_the_ball/srv/Throw.srv
 *
 */


#ifndef CATCH_THE_BALL_MESSAGE_THROW_H
#define CATCH_THE_BALL_MESSAGE_THROW_H

#include <ros/service_traits.h>


#include <catch_the_ball/ThrowRequest.h>
#include <catch_the_ball/ThrowResponse.h>


namespace catch_the_ball
{

struct Throw
{

typedef ThrowRequest Request;
typedef ThrowResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Throw
} // namespace catch_the_ball


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::catch_the_ball::Throw > {
  static const char* value()
  {
    return "0d454b12faaf5b34cc431d6fe22cf601";
  }

  static const char* value(const ::catch_the_ball::Throw&) { return value(); }
};

template<>
struct DataType< ::catch_the_ball::Throw > {
  static const char* value()
  {
    return "catch_the_ball/Throw";
  }

  static const char* value(const ::catch_the_ball::Throw&) { return value(); }
};


// service_traits::MD5Sum< ::catch_the_ball::ThrowRequest> should match 
// service_traits::MD5Sum< ::catch_the_ball::Throw > 
template<>
struct MD5Sum< ::catch_the_ball::ThrowRequest>
{
  static const char* value()
  {
    return MD5Sum< ::catch_the_ball::Throw >::value();
  }
  static const char* value(const ::catch_the_ball::ThrowRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::catch_the_ball::ThrowRequest> should match 
// service_traits::DataType< ::catch_the_ball::Throw > 
template<>
struct DataType< ::catch_the_ball::ThrowRequest>
{
  static const char* value()
  {
    return DataType< ::catch_the_ball::Throw >::value();
  }
  static const char* value(const ::catch_the_ball::ThrowRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::catch_the_ball::ThrowResponse> should match 
// service_traits::MD5Sum< ::catch_the_ball::Throw > 
template<>
struct MD5Sum< ::catch_the_ball::ThrowResponse>
{
  static const char* value()
  {
    return MD5Sum< ::catch_the_ball::Throw >::value();
  }
  static const char* value(const ::catch_the_ball::ThrowResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::catch_the_ball::ThrowResponse> should match 
// service_traits::DataType< ::catch_the_ball::Throw > 
template<>
struct DataType< ::catch_the_ball::ThrowResponse>
{
  static const char* value()
  {
    return DataType< ::catch_the_ball::Throw >::value();
  }
  static const char* value(const ::catch_the_ball::ThrowResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CATCH_THE_BALL_MESSAGE_THROW_H
